### ISSUE TITLE
Project Apollo - the blueprint for the first version

### ISSUE THREAD

**Issue by idiotWu** [service-mocker/service-mocker#1]
Hey guys, welcome to the future! This is the outline of service mocker.

### API mock service sucks

Generally, there are two ways to mock an API for your front-end projects:

1. Set up a temporary server to provide the mock data.
2. Write mock data directly in your codes.

For the first one, you may have to do tons of works just to set up a simple server. And for the second one, you have to pollute your codes with fake data. What if there's a magic that allows you to mock in front-end and act just like a real server?

Today, with the service worker API, we can find out a way to intercept requests and respond with real HTTP responses that are generated in the service worker context. That's the main idea of this project.

### Advantages

1. Easy to set up.
2. Real requests that can be inspected in dev tools.
3. No proxies, no separate server addresses, no CORS issues, no pains.

### Disadvantages

1. Poor compatibility: http://caniuse.com/#feat=serviceworkers
2. Weird behaviors among old version of browsers.

## 0x01 - Infrastructure

In an ideal world, only scripts for service workers are needed for running a requests interceptor. But as there are so many limitations with service worker, we are likely to wrap a client runtime for it.

- Client
  - storage
  - service worker updater
- Server
  - router
  - request and response layers
  - storage service

## 0x02 - Features List

- Client
  - [x] real-time sw scripts updater, #2 
  - [x] legacy browers support, #5 

- Server
  - [x] express-style router module
  - [x] request layer
  - [x] response layer

CC @VincentBel

**Comment by idiotWu** [comment]
v1.0.0 is out 👏
