### ISSUE TITLE
Project Phoenix - roadmap of ver. 2

### ISSUE THREAD

**Issue by idiotWu** [service-mocker/service-mocker#29]
Hey guys, we got some problems.

### Ⅰ. The default libs in TypeScript are not perfect

Neither ts2.2 nor ts2.3 provides complete typings for service workers. What's more, they mixed together service worker context and worker context, which brings some other issues to us :/

### II. Compilations across multiple contexts are difficult 

`service-mocker` contains two parts: `client` for DOM side and `server` for service worker side. However, `lib.dom` and `lib.worker` are mutually exclusive. So we have to create multiple separate compilations, which cause unnecessary complexity.

### Multiple compilations

As argued above, multiple compilations bring unnecessary complexity to us. @VincentBel has been working on [support-ts2.2](https://github.com/service-mocker/service-mocker/tree/support-ts2.2) branch for long but still can not get a perfect workaround. The duplicate compilations of shared parts, i.e. `constants/` and `utils/`, seem to be unavoidable.

Besides, [the lack of typings](https://github.com/service-mocker/service-mocker/blob/support-ts2.2/src/server/missing-service-worker-typing.d.ts) also causes headaches. And it's considered hard to maintenance those typings with the monthly release of TypeScript.

### Switch to Babel + Flow

As an alternation of TypeScript, [Flow](https://flow.org) is still immature now. We couldn't even find a proper plugin or tool for our editors. Life is short, don't waste your time fighting against tools 🙃 .

## 0x02 - v2, and future

So as a result, we'd like to **rewrite this project with Babel**. We may switch back to TypeScript or Flow some day, but first of all, our goal is to solve the problems in daily development ;)

## 0x03 - TODO

- [x] Refactor with babel. (#30)
- [x] Standalone typings file. (#33)
- [x] Publish a patch release for TypeScript compatibility check in v1.x.
- [x] Release v2.0.0.

CC @VincentBel
